#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_accueil:

  path: /
  controller: App\Controller\AccueilController::index


#app_ComptableConnexion:
#  path: /Comptable/Connexion
#  controller: App\Controller\ComptableController::connexion

app_VisiteurConnexion:
  path: /Visiteur/Connexion
  controller: App\Controller\VisiteurController::connexion

  app_VisiteurConnecter:
  path: /Visiteur/Connecter
  controller: App\Controller\VisiteurController::connecter