<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB2hj492\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB2hj492/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB2hj492.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB2hj492\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB2hj492\App_KernelDevDebugContainer([
    'container.build_hash' => 'B2hj492',
    'container.build_id' => 'a9e952f1',
    'container.build_time' => 1669314508,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB2hj492');
